//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.RemoteBetterplaceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteBetterplaceReference.IRemoteRoutePlanner")]
    public interface IRemoteRoutePlanner {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteRoutePlanner/getGraph", ReplyAction="http://tempuri.org/IRemoteRoutePlanner/getGraphResponse")]
        DataTier.Graph getGraph();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRemoteRoutePlannerChannel : Client.RemoteBetterplaceReference.IRemoteRoutePlanner, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteRoutePlannerClient : System.ServiceModel.ClientBase<Client.RemoteBetterplaceReference.IRemoteRoutePlanner>, Client.RemoteBetterplaceReference.IRemoteRoutePlanner {
        
        public RemoteRoutePlannerClient() {
        }
        
        public RemoteRoutePlannerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteRoutePlannerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteRoutePlannerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteRoutePlannerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataTier.Graph getGraph() {
            return base.Channel.getGraph();
        }
    }
}
